# Generated by Django 4.1.10 on 2023-08-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theweather', '0004_alter_choice_question_alter_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
