# Generated by Django 4.1.10 on 2023-08-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='teste',
            field=models.SmallIntegerField(null=True),
        ),
    ]
