# Generated by Django 4.1.10 on 2023-08-27 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 27, 3, 11, 8, 994087, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
